config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :counters

  map.resources :planworkhours

  map.resources :planworktools

  map.connect '/maintreports/new_up', :controller => 'maintreports', :action => 'new_up'
  map.connect '/maintreports/show_up', :controller => 'maintreports', :action => 'show_up'
  map.resources :maintreports

  map.resources :jobdescs

  map.resources :orgcharts

  map.resources :locations

  map.connect '/maintgroups/prt_group_list', :controller => 'maintgroups', :action => 'prt_group_list'
  map.resources :maintgroups

  map.connect '/maintenances/show_up', :controller => 'maintenances', :action => 'show_up'
  map.connect '/maintenances/edit_up', :controller => 'maintenances', :action => 'edit_up'
  map.connect '/maintenances/newunplan', :controller => 'maintenances', :action => 'newunplan'
  map.connect '/maintenances/index_up', :controller => 'maintenances', :action => 'index_up'
  map.connect '/maintenances/planner', :controller => 'maintenances', :action => 'planner'
  map.connect '/maintenances/planner_prt', :controller => 'maintenances', :action => 'planner_prt'
  map.resources :maintenances, :member => { :show_up => [:get, :post, :put] }
  map.resources :maintenances, :member => { :index_up => [:get] }
  map.resources :maintenances, :member => { :planner => [:get] }
  map.resources :maintenances

  map.resources :documents
  
  map.connect '/parts/prt_parts_list', :controller => 'parts', :action => 'prt_parts_list'
  map.resources :parts

  map.connect '/addresses/prt_group_list', :controller => 'addresses', :action => 'prt_add_list'
  map.resources :addresses

  map.connect '/tools/prt_tools_list', :controller => 'tools', :action => 'prt_tools_list'
  map.resources :tools
  
  map.connect '/components/prt_eqpt_list', :controller => 'components', :action => 'prt_eqpt_list'
  map.resources :components, :collection => { :indextree => :get }

  map.resources :roles

  
  
  map.logout '/logout', :controller => 'sessions',  :action => 'destroy'
  map.login '/login',   :controller => 'sessions',  :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users',     :action => 'new'
  
  map.resources :users

  map.resource :session

  
  
  map.about '/about', :controller => "pages", :action => 'about'

  

  map.root :controller => "pages", :action => 'home'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  
  has_and_belongs_to_many :roles

  validates_presence_of     :login
  validates_length_of       :login,    :within => 3..40
  validates_uniqueness_of   :login
  validates_format_of       :login,    :with => Authentication.login_regex, :message => Authentication.bad_login_message

  validates_format_of       :name,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message, :allow_nil => true
  validates_length_of       :name,     :maximum => 100

  validates_presence_of     :email
  validates_length_of       :email,    :within => 6..100 #r@a.wk
  validates_uniqueness_of   :email
  validates_format_of       :email,    :with => Authentication.email_regex, :message => Authentication.bad_email_message

  

  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  #attr_accessible :login, :email, :name, :password, :password_confirmation
  cattr_accessor :current_user

  #edit here
  has_many  :editors,   :class_name => 'Components',     :foreign_key => 'created_by'
  has_many  :maintenance, :foreign_key => 'reported_by'
  
  def role_symbols
    roles.map do |role|
      role.authname.to_sym
    end
  end
  #edits close

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Be sure to include AuthenticationSystem in Application Controller instead
  
  
  before_filter :set_page_title
  
  def set_page_title
    @pagetitle = t('user')
  end

  def index
    @users= User.find(:all)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to(users_url)
  end
  
  def edit
     @user = User.find(params[:id])
  end
  
  def update
     @user = User.find(params[:id])
     
     if @user.update_attributes(params[:user])
       flash[:notice] = "User was successfully updated"
       redirect_to(user_path(@user))
     else
       render :action => :edit
     end
  end
  
  # render new.rhtml
  def new
    @user = User.new
  end
 
  def create
    logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
      # Protects against session fixation attacks, causes request forgery
      # protection if visitor resubmits an earlier form using back
      # button. Uncomment if you understand the tradeoffs.
      # reset session
      self.current_user = @user # !! now logged in
      redirect_back_or_default('/')
      flash[:notice] = "Thanks for signing up!  We're sending you an email with your activation code."
    else
      flash[:error]  = "We couldn't set up that account, sorry.  Please try again, or contact an admin (link is above)."
      render :action => 'new'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_form.html.erb
<div class='webform'>
<table>
	<tr>
		<th colspan=2>Add / Edit User</th>
	</tr>
	<tr>
    <td class=leftcol>Name:</td>
    <td><%= f.text_field :name %></td>
  </tr>
	<tr>
    <td class=leftcol>Login:</td>
    <td><%= f.text_field :login %></td>
  </tr>
  <tr>
    <td class=leftcol>Email:</td>
    <td><%= f.text_field :email %></td>
  </tr>
	<tr>
    <td class=leftcol>Password:</td>
    <td><%= f.password_field :password %></td>
  </tr>
	<tr>
    <td class=leftcol>Confirm Password:</td>
    <td><%= f.password_field :password_confirmation %></td>
  </tr>
</table>
<table>
	<tr>
		<th>User Roles</th>
	</tr>
</table>
<table>
	<tr>
	<% for role in Role.find(:all) %>
		<td width=25px ALIGN="center"><%= role.name %></td>
	<% end %>
	  <td></td>
	</tr>
	<tr>
	<% for role in Role.find(:all) %>
		<td ALIGN="center"><%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %></td>
	<% end %>
	  <td></td>
	</tr>
	
</table>

</div>

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/edit.html.erb
	<% form_for(@user) do |f| %>
	<%= f.error_messages %>

	  <%= render :partial => 'form', :locals => {:f => f}   %>

	  <p>
	    <%= f.submit 'Update' %>
	  </p>
	<% end %>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="box">
	<div class="box-head">
		<h2 class="left">Users</h2>
		<div class="right">
		</div>
	</div>
</div>

<div class="indexlist">
<% link_to 'Create New role', new_user_path %>
<table>
  <tr>
    <th><%= link_to image_tag("add.png", :border => 0, :title => 'Create'), new_user_path %> Users </th>
    <th>Log-In</th>
		<th>e-mail address</th>
    <th colspan=3>Control</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.name %></td>
		<td><%=h user.login %></td>
		<td><%=h user.email %></td>
		<td width=10px><%= link_to image_tag("document.png", :border => 0, :title => 'Show'), :action => 'show', :id => user %></td>
    <td width=10px><%= link_to image_tag("edit.png", :border => 0, :title => 'Edit'), :action => 'edit', :id => user %></td>
    <td width=10px><%= link_to image_tag("delete.png", :border => 0, :title => 'Delete'), user, :confirm => "Are you sure you want to delete '#{user.name}'?", :method => :delete %>
  </tr>
<% end %>
</table>

<br />



</div>

app/views/users/new.html.erb
<% @user.password = @user.password_confirmation = nil %>

<%= error_messages_for :user %>
<% form_for :user, :url => users_path do |f| -%>

  <%= render :partial => 'form', :locals => {:f => f}   %>
  <p>
    <%= submit_tag 'Sign up' %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="showform">
	
	<H2>Users</H2>
	
	<fieldset>
		<legend>Details</legend>
		<table>
			<tr>
		    <td class="leftcol">Name:</td>
		    <td><%=h @user.name %></td>
		  </tr>
			<tr>
		    <td class=leftcol>Login:</td>
		    <td><%=h @user.login %></td>
		  </tr>
			<tr>
		    <td class=leftcol>Email:</td>
		    <td><%=h @user.email %></td>
		  </tr>
			<tr>
		    <td class=leftcol>Password:</td>
		    <td>[secret]</td>
		  </tr>
			<tr>
		    <td class=leftcol>User Roles:</td>
		    <td><% for role in @user.roles %><%=h role.name %>, <% end %></td>
		  </tr>
		</table>
	</fieldset>
	
	<fieldset>
		<legend>Record Details</legend>  <!--  Just break into logical groups for easy viewing-->
		<table>
			<tr>
		    <td class=leftcol>Last Edit On:</td>
		    <td><%=h l(@user.updated_at) %></td>
		  </tr>
			<tr>
		    <td class=leftcol>Created On:</td>
		    <td><%=h l(@user.created_at) %></td>
		  </tr>

		</table>
	</fieldset>
		
</div>

	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back', users_path %>
	